sudo: required
dist: trusty

language: python

python:
  - "2.7_with_system_site_packages"
  - "3.5"

addons:
  apt:
    packages:
      - network-manager

env:
  - TOX_ENV=py
  - TOX_ENV=flake8

before_install:
  - "sudo apt-get update -qq"

install:
  - "pip install tox"

script:
  - "tox -e $TOX_ENV"

deploy:
  provider: pypi
  user: $pip_user
  password: $pip_pass
  skip_existing: true
